
CREATE TABLE cartoon (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  img VARCHAR(255) NULL, 
  name VARCHAR(255) NOT NULL);


CREATE TABLE toys (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
img VARCHAR(255) NULL, 
release_date DATE NULL, 
manufacturer VARCHAR(255) NOT NULL, 
cartoon_id INT,
CONSTRAINT fk_toys_cartoon     
FOREIGN KEY (cartoon_id)
REFERENCES cartoon(id)
);
